// const {
//     saveReferral,
//     updateReferralStatus,
//     getReferralById
// } = require("../services/firebaseService");

// const {

//     sendReferralSMS

// } = require("../services/smsService");

// const createReferral = async (req, res) => {

//     try {

//         // Step 1: Save referral
//         const referralId = await saveReferral(req.body);

//         let smsResult = null;

//         // Step 2: Send SMS only if urgent
//         if (req.body.risk.level === "URGENT") {

//             smsResult = await sendReferralSMS(req.body);

//             if (smsResult.success) {

//                 await updateReferralStatus(
//                     referralId,
//                     smsResult.status,
//                     smsResult.sid
//                 );

//             } else {

//                 await updateReferralStatus(
//                     referralId,
//                     "failed"
//                 );

//             }

//         }

//         return res.status(201).json({

//             success: true,

//             referralId,

//             sms: smsResult

//         });

//     } catch (error) {

//         console.error(error);

//         return res.status(500).json({

//             success: false,

//             message: "Internal Server Error"

//         });

//     }

// };

// const getReferral = async (req, res) => {

//     try {

//         const referralId = req.params.id;

//         const referral = await getReferralById(referralId);

//         if (!referral) {

//             return res.status(404).json({

//                 success: false,

//                 message: "Referral not found"

//             });

//         }

//         return res.status(200).json({

//             success: true,

//             referral

//         });

//     } catch (error) {

//         console.error(error);

//         return res.status(500).json({

//             success: false,

//             message: "Internal Server Error"

//         });

//     }

// };

// module.exports = {
//     createReferral,
//     getReferral
// };

const {
    saveReferral,
    updateReferralStatus,
    getReferralById,
    getIncomingReferrals,
    updateReferralLifecycleStatus
} = require("../services/firebaseService");

const {
    sendReferralSMS
} = require("../services/smsService");


const createReferral = async (req, res) => {

    try {

        // Prepare referral data
        const referral = {
            ...req.body,

            // Hospital information
            hospitalId: "dist-hospital-1",

            // Demo ETA
            eta: 75,

            // Referral status
            referralStatus: "sent",

            // What the patient needs
            patientNeeds: req.body.patientNeeds || [],

            // Will be generated by AI later
            recommendedActions: req.body.recommendedActions || []
        };


        // Step 1: Save referral
        const referralId = await saveReferral(referral);

        let smsResult = null;


        // Step 2: Send SMS only if urgent
        if (referral.risk.level === "URGENT") {

            smsResult = await sendReferralSMS(referral);


            // SMS successfully accepted by Twilio
            if (smsResult.success) {

                await updateReferralStatus(
                    referralId,
                    smsResult.status,
                    smsResult.sid
                );

            }

            // SMS failed
            else {

                await updateReferralStatus(
                    referralId,
                    "failed"
                );

            }

        }


        // Step 3: Return response
        return res.status(201).json({

            success: true,

            referralId,

            sms: smsResult

        });

    } catch (error) {

        console.error(error);

        return res.status(500).json({

            success: false,

            message: "Internal Server Error"

        });

    }

};


const getReferral = async (req, res) => {

    try {

        const referralId = req.params.id;

        const referral = await getReferralById(referralId);


        if (!referral) {

            return res.status(404).json({

                success: false,

                message: "Referral not found"

            });

        }


        return res.status(200).json({

            success: true,

            referral

        });

    } catch (error) {

        console.error(error);

        return res.status(500).json({

            success: false,

            message: "Internal Server Error"

        });

    }

};

const getIncoming = async (req, res) => {

    try {

        const referrals = await getIncomingReferrals();

        return res.status(200).json({

            success: true,

            count: referrals.length,

            referrals

        });

    } catch (error) {

        console.error("Error fetching incoming referrals:", error);

        return res.status(500).json({

            success: false,

            message: "Failed to fetch incoming referrals"

        });

    }

};


const updateReferralLifecycle = async (req, res) => {

    try {

        const referralId = req.params.id;

        const { status } = req.body;


        // Allowed statuses
        const allowedStatuses = [
            "sent",
            "acknowledged",
            "arrived",
            "checked_in"
        ];


        // Check status exists
        if (!status) {

            return res.status(400).json({

                success: false,

                message: "Status is required"

            });

        }


        // Check status is valid
        if (!allowedStatuses.includes(status)) {

            return res.status(400).json({

                success: false,

                message: "Invalid referral status"

            });

        }


        // Get current referral
        const referral = await getReferralById(referralId);


        if (!referral) {

            return res.status(404).json({

                success: false,

                message: "Referral not found"

            });

        }


        // Current status
        const currentStatus =
            referral.referralStatus;


        // Allowed transitions
        const validTransitions = {

            sent: ["acknowledged"],

            acknowledged: ["arrived"],

            arrived: ["checked_in"],

            checked_in: []

        };


        // Check transition
        if (
            currentStatus !== status &&
            !validTransitions[currentStatus]?.includes(status)
        ) {

            return res.status(400).json({

                success: false,

                message:
                    `Cannot change referral status from ${currentStatus} to ${status}`

            });

        }


        // Update Firestore
        await updateReferralLifecycleStatus(
            referralId,
            status
        );


        return res.status(200).json({

            success: true,

            referralId,

            referralStatus: status

        });

    } catch (error) {

        console.error(
            "Error updating referral status:",
            error
        );

        return res.status(500).json({

            success: false,

            message: "Failed to update referral status"

        });

    }

};


module.exports = {
    createReferral,
    getReferral,
    getIncoming,
    updateReferralLifecycle
};